microsoft/Nova

- src/commitments.rs
- src/lib.rs
- src/r1cs.rs
- src/traits.rs
and cleanup some group op traits
> generic traits for prime field elements and group elements

- Cargo.toml
- src/lib.rs
- src/pasta.rs
Now that https://github.com/zcash/pasta_curves is licensed under MIT/Apache, we can depend on it directly here. This simplifies trait definitions (which previously had to be wrapped, with duplicate implementations of standard operations, when providing) for pasta curves.
I removed the dev dependency on Ristretto under the assumption that it was only a placeholder whose purpose could be served by Pasta now. This allowed upgrading the rand dependency, which is useful downstream.
> Support Pasta curves.

- src/errors.rs
- src/r1cs.rs
Add a new error, `InputOutputMismatch` for the case in which the current input and previous output do not match, when folding instances.
> Add InputOutputMismatch error.

- Cargo.toml
PR to use the latest bellperson, which supports 'instance aggregation' and is needed to allow Groth16 proofs somewhat structurally comparable to Nova proofs.
> Use bellperson v0.19.0.

- src/bellperson/r1cs.rs
- src/bellperson/solver.rs
- tests/num.rs
This PR adds tests that @srinathsetty provided in `tests/num.rs`. Prior to the fixes here, `test_use_cs_one` was failing.
```
running 2 tests
test test_use_cs_one ... FAILED
test test_use_cs_one_after_inputize ... ok
failures:
---- test_use_cs_one stdout ----
thread 'test_use_cs_one' panicked at 'index out of bounds: the len is 0 but the index is 0', /Users/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/bellperson-0.19.1/src/lc.rs:257:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failures:
test_use_cs_one
```
It passes now, and I believe the fix is correct. The problem was that the 'one' input was not being added, so constraints referencing it were trying to index into the 0th position of a 0-element vector if no other inputs had yet been added. …
> Fix CS::one() bug in solver.

- src/lib.rs
We currently implement a constant-factor compression, but in the future we will provide an exponential reduction in proof sizes
> IVC proof compression APIs and implementation

- examples/minroot.rs
- src/commitments.rs
- src/lib.rs
- src/pasta.rs
- src/r1cs.rs
- src/traits/mod.rs
* Avoid committing to zero vectors when creating a default instance
* Make 3 constraints/iter (down from 4 constraints/iter) in the MinRoot example
> Optimizations

- examples/minroot.rs
Avoid allocating unneeded advice variables
Run with multiple MinRoot iterations per Nova step in a loop
> optimize MinRoot constraint system

- Cargo.toml
- src/pasta.rs
Adds fast, parallelisable MSM for compile targets that aren't supported by pasta_msm/semolina. Also uses fast MSM on small MSMs (smaller than 128 size) for _all_ architecture since I'm on my laptop a size 128 MSM is ~3x faster with this code vs. the old non Pippengers code.
The multiexp code is taken from https://github.com/zcash/halo2/blob/main/halo2_proofs/src/arithmetic.rs, all credits to authors there!
Tested end to end with this branch of Nova Scotia: https://github.com/nalinbhardwaj/Nova-Scotia/tree/browser
Follow up from discussion here: https://github.com/microsoft/Nova/pull/125#discussion_r1087001908
> Speed up MSMs for non-GPU accelerated MSMs and architectures that don't support GPU/semolina

- Cargo.toml
- benches/compressed-snark.rs
- benches/recursive-snark.rs
- examples/minroot.rs
- examples/signature.rs
- src/bellperson/shape_cs.rs
- src/bellperson/solver.rs
- src/circuit.rs
- src/gadgets/ecc.rs
- src/gadgets/nonnative/bignat.rs
- src/gadgets/nonnative/util.rs
- src/gadgets/r1cs.rs
- src/gadgets/utils.rs
- src/poseidon.rs
- Uses captured string identifiers as introduced in [Rust 1.58](https://blog.rust-lang.org/2022/01/13/Rust-1.58.0.html#captured-identifiers-in-format-strings)
- Removes default features for bellperson and neptune, as they only pull in groth16
> Clippy formatting

- .github/workflows/rust.yml
- Cargo.toml
Adds features `cuda` and `opencl` to toggle Neptune to compile and use GPU kernels. On https://github.com/nalinbhardwaj/Nova-Scotia/pull/6 this is a ~10% speedup on a larger circuit on my 2018 MacBook (so likely significant on better machines/GPU as well).
> Feature to enable Neptune GPU Poseidon

- README.md
- src/lib.rs
- src/traits/circuit.rs
Fixed a minor typo I think.
The length check of z0 is done twice.
(Note: This is my first pull request in my life. I'm sincerely sorry if I missed a practice that should be followed in git and caused any inconvenience.)
> minor typo fix

- src/gadgets/ecc.rs
- src/provider/pasta.rs
This PR makes the ECC tests generic wrt to the curves, as long as a curve implements `nova::traits::Group`, `pasta_curves::arithmetic::CurveAffine` (which is the case for the curves in `halo2curves`, eg), and the `Base` and `Scalar` fields are shared between the traits.
After https://github.com/microsoft/Nova/pull/162 is merged, we can implement other curve cycles and use them directly in the tests such as in https://github.com/microsoft/Nova/commit/8e70bfca67f77bcfd6de5261d76a52fefdcfa951.
> Make ecc tests generic wrt curves

- src/bellperson/mod.rs
- src/circuit.rs
- src/gadgets/ecc.rs
- src/lib.rs
- src/nifs.rs
- src/provider/keccak.rs
- src/provider/poseidon.rs
- src/spartan/pp.rs
Makes ~bellperson, ivc, circuit, nifs~ all tests generic in the type of the involved curves. 
This PR is a descendent of #165 should greatly help testing Nova w/ another curve cycle. (/cc @leonardoalt)
This shows a bit of (acceptable) non-genericity in the ivc tests, in that we rely on the `CommitmentKeyExt` trait being implemented to allow usage of the IPA as a PC. I'm not sure this is inherently necessary, but perhaps we can lift this restriction in another PR.
> [test-only] More genericity in tests

- Cargo.toml
- Update neptune dependency to version 10.0.0
This imports a bug-fix for the serializer of `PoseidonConstants`, which is used in Lurk to cache Nova's public parameters.
> chore: Update neptune dependency

- src/gadgets/ecc.rs
- src/nifs.rs
- make `test_tiny_r2cs` (will help with upcoming adaptation to other curve cycles)
- fix a [`redundant_clone`](https://rust-lang.github.io/rust-clippy/master/index.html#/redundant_clone) clippy warning, closes #178
> [test, chore]: Fix clippy and genericize one more test

- Cargo.toml
- benches/compute-digest.rs
- src/lib.rs
The Zlib compression of a byte string is not a reproducible artefact across implementations, as can be verified by taking the next-to-last commit of this PR ( c79f4f66a72fe75b59309c03ec24da094b27a8ef ), i.e. reducing the PR to just adding a test and a bench, and trying the following:
- using one of the three non-default backends for the flate2 import, as indicated [here](https://github.com/rust-lang/flate2-rs#backends)
- using gzp with [this commit](https://github.com/microsoft/Nova/commit/45e22aa9a71335b4b0115ccc92f9395bb594f651)
- using libdeflater with [this commit](https://github.com/microsoft/Nova/commit/14aabfe2984abb8b3c3027a56571a5793b5c4d55)
The 5 implementations of Zlib above will all fail to pass the test and return distinct values (not only w.r.t the test, but also w.r.t *each …
> Remove Zlib compression in public parameter computation

- Cargo.toml
- benches/compressed-snark.rs
- benches/recursive-snark.rs
- examples/minroot.rs
- src/gadgets/ecc.rs
- src/lib.rs
- src/provider/pedersen.rs
Im try to minimize the cost to `.copy()`, `.clone()` multiple structures around. You might expect ~10% in total performance and ~5% in memory saving.
2 tests are broken, so I'm try to fix it. If this worth, please let me know.
> Improve performance of recursive

- .github/workflows/rust.yml
- Cargo.toml
- benches/compressed-snark.rs
- benches/recursive-snark.rs
See https://www.jibbow.com/posts/criterion-flamegraphs/
> Add the ability to profile the benchmarks w/ a flamegraph feature 

- benches/compressed-snark.rs
- benches/recursive-snark.rs
- examples/signature.rs
- src/bellperson/shape_cs.rs
- src/bellperson/solver.rs
- src/circuit.rs
- src/gadgets/ecc.rs
- src/gadgets/nonnative/bignat.rs
- src/gadgets/r1cs.rs
- src/gadgets/utils.rs
- src/lib.rs
- src/provider/poseidon.rs
- src/spartan/mod.rs
- src/spartan/pp.rs
- src/spartan/sumcheck.rs
I didn't quite have a place to put those as I was reading / refactoring other bits: opinions on those loosely held, happy to adjust.
The commit are tailored to be independent, and the individual commit messages are meant to be informative.
No serious effect on benchmarks, one way or another:
https://gist.github.com/huitseeker/93c66fda2f8444870e9374da990de541
> [refactorings] Leftovers (pot-pourri?)

- Cargo.toml
- benches/sha256.rs
This adds a single step of folding a Sha-256 at varied input lengths.
> Add a Sha256 bench

- Cargo.toml
- src/bellperson/mod.rs
- src/circuit.rs
- src/gadgets/ecc.rs
- src/lib.rs
- src/nifs.rs
- src/provider/bn254_grumpkin.rs
- src/provider/bn256_grumpkin.rs
- src/provider/keccak.rs
- src/provider/mod.rs
- src/provider/pasta.rs
- src/provider/poseidon.rs
- src/spartan/pp.rs
This is joint work with @leonardoalt !
This PR pulls in an implementation of, and runs all Nova tests on the [Ethereum-friendly Grumpkin curve cycle](https://hackmd.io/@aztec-network/ByzgNxBfd#2-Grumpkin---A-curve-on-top-of-BN-254-for-SNARK-efficient-group-operations). 
The implementation ~~is~~ was  from the halo2curves repo with the following pending PR thrown in:
https://github.com/privacy-scaling-explorations/halo2curves/pull/47 - ~~I'll update the present PR when that resolves.~~
> Add Grumpkin cycle implementation

- src/provider/keccak.rs
The Keccak transcript implementation can allocate a potentially very long vector by storing a full copy of the transcript and hashing it only on a state update. This computation can instead be performed incrementally at the cost of putting the transcript at the start of `squeeze`'s input, only storing the (bounded) state of the hasher.
This improves the memory usage, and has no significant effect on benchmarks:
https://gist.github.com/huitseeker/b5bc1df2e012dcca1356b4c1ad251eee
- Replaced the transcript vector with a `Keccak256` instance, improving data handling and memory usage.
- Refactored `compute_updated_state` to work directly on a given `Keccak256` instance, reducing unnecessary object creation.
- this change ~~roughly~~ amounts to putting the transcript at the start of squeeze's …
> refactor: Refactor Keccak256Transcript and update tests

- src/provider/pedersen.rs
- Refactored the `CommitmentKeyExtTrait` from the local `src/provider/pedersen.rs` to the more centrally located `src/traits/commitment.rs`.
- Updated `src/provider/ipa_pc.rs` to import `CommitmentKeyExtTrait` directly from its new location in the `commitment` module.
The current `CommitmentKeyExtTrait` must be referred to - if not implemented - by any code base that wants to be generic in the curve cycle that's used in Nova, as #171 demonstrated. In the current state, this trait was crate-private, and could not be referred to, even by projects that would want to write code *only* for the two curve cycles the Nova code base already supports.
> refactor: make CommitmentKeyExtTrait public

- benches/compressed-snark.rs
This benchmarks the computation commitments (see Spartan, section 6) introduced in #152 and re-engineered in #158.
Sample benchmark run:
https://gist.github.com/huitseeker/b284551b6a40a7c0225f093a94a7f64c
> Benchmark computation commitments

- src/r1cs.rs
- src/spartan/ppsnark.rs
- src/spartan/snark.rs
- src/spartan/sumcheck.rs
- src/traits/commitment.rs
- src/traits/mod.rs
Removes a bit of code duplication in a couple files.
> Small code organization improvements

- Cargo.toml
- benches/compressed-snark.rs
- benches/compute-digest.rs
- benches/recursive-snark.rs
- benches/sha256.rs
- examples/minroot.rs
- src/circuit.rs
- src/gadgets/ecc.rs
- src/gadgets/nonnative/util.rs
- src/lib.rs
- src/provider/ipa_pc.rs
- src/provider/pasta.rs
- src/spartan/polynomial.rs
This optimizes redundant memory allocations away.
> Remove uneeded circuit allocations in RecursiveSNARK

- benches/compressed-snark.rs
- benches/compute-digest.rs
- benches/recursive-snark.rs
- benches/sha256.rs
- examples/minroot.rs
- src/circuit.rs
- src/errors.rs
- src/gadgets/r1cs.rs
- src/lib.rs
- src/provider/poseidon.rs
- src/spartan/direct.rs
- src/traits/circuit.rs
- src/traits/mod.rs
- fine tune step circuit to optional `output` function, which potentially lead to duplicate logic with synthesis function.
- optimize RO trait to take reference, further optimize memory usage.
> fine tune step circuit trait to avoid re-implement zi->zi_next logic

- src/gadgets/ecc.rs
- src/spartan/mod.rs
- src/spartan/polynomial.rs
This is a smaller PR that is cut out from larger work of implementing HyperNova https://github.com/microsoft/Nova/pull/175 (latest live version is here https://github.com/privacy-scaling-explorations/nova)
A problem that occurred when we were implementing HyperNova is that we didn't fully understand the embedded spartan/polynomial.rs code, and thus reached for other tools such as can be seen here https://github.com/microsoft/Nova/pull/175#discussion_r1267090563
By adding better documentation and tests for this module it is easier to understand what is going on.
This PR:
- Add documentation to spartan/polynomial.rs file
- Make polynomial crate public to easily generate docs and encourage API use
- Add Add trait and scalar_mul method
- Add tests for polynomial functions
> feat(spartan/polynomial): Update polynomial with docs and new methods

- Cargo.toml
- benches/compressed-snark.rs
- benches/compute-digest.rs
- benches/recursive-snark.rs
- benches/sha256.rs
- examples/minroot.rs
- examples/signature.rs
- src/bellperson/mod.rs
- src/bellperson/r1cs.rs
- src/bellperson/shape_cs.rs
- src/bellperson/solver.rs
- src/circuit.rs
- src/gadgets/ecc.rs
- src/gadgets/nonnative/bignat.rs
- src/gadgets/nonnative/mod.rs
- src/gadgets/nonnative/util.rs
- src/gadgets/r1cs.rs
- src/gadgets/utils.rs
- src/lib.rs
- src/nifs.rs
- src/provider/poseidon.rs
- src/spartan/direct.rs
- src/traits/circuit.rs
- src/traits/mod.rs
- The `bellperson` library has been replaced maximally (see below) with `bellpepper_core` throughout the project,
- The changes involved updating all import statements across various source, benchmark, and example files, while maintaining the same functionality.
- By way of upgrade, some functions have been refactored to operate with referenced variables rather than owning their variables, improving memory efficiency.
Before this PR:
```mermaid
graph LR;
A[bellperson] --> B[neptune];
B --> C[Nova];
A --> C;
```
After ~~neptune is released (and~~ https://github.com/filecoin-project/bellperson/pull/314 is ~~merged &~~ released ~~)~~, this PR installs:
```mermaid
graph LR;
A[bellpepper] --> B[neptune];
B --> C[Nova];
A --> C;
D[bellperson] --> C;
```
Once #177 is rebased on the present PR …
> chore: Switch dependency from `bellperson` to `bellpepper_core` & `bellpepper` (PoC)

- src/bellpepper/mod.rs
- src/bellpepper/r1cs.rs
- src/bellpepper/shape_cs.rs
- src/bellpepper/solver.rs
- src/bellpepper/test_shape_cs.rs
- src/circuit.rs
- src/gadgets/ecc.rs
- src/lib.rs
- src/nifs.rs
- src/provider/poseidon.rs
- src/spartan/direct.rs
This PR completes the transition from bellperson to bellpepper, renaming all references in code, comments, and files/directories.
> Rename bellperson to bellpepper everywhere.

- Cargo.toml
- examples/signature.rs
- src/circuit.rs
- src/gadgets/r1cs.rs
- src/lib.rs
- src/provider/ipa_pc.rs
- src/r1cs.rs
- src/spartan/mod.rs
- src/spartan/polynomial.rs
- src/spartan/ppsnark.rs
- src/spartan/snark.rs
- src/spartan/sumcheck.rs
The individual commit messages should detail the changes:
- remove itertools, only used for a function that's available in the std,
- remove a few needless pass-by-value instances,
- remove the roundtrip to f64 when computing a log2, replaces by the std `ilog2`,
- refactor padding to avoid reallocation,
- tweak a constant definition.
> Various refactorings

- Cargo.toml
- benches/compressed-snark.rs
- benches/compute-digest.rs
- benches/recursive-snark.rs
- benches/sha256.rs
- src/lib.rs
- src/nifs.rs
- src/provider/bn256_grumpkin.rs
- src/provider/ipa_pc.rs
- src/provider/keccak.rs
- src/provider/pedersen.rs
- src/spartan/direct.rs
- src/spartan/ppsnark.rs
- src/spartan/snark.rs
- src/traits/commitment.rs
- src/traits/evaluation.rs
- src/traits/mod.rs
The individual commit messages are meant to be meaningful. At a high level:
-  starts leveraging `zkcrypto/group` to simplify trait definitions (see #198, but consider this only reuses the blanket impl of a convenience trait referring to `std::ops`), 
- removes unneeded trait bounds (this is backwards-compatible), 
- removes unneeded `Phantom` types,
- updates `halo2curves` with the recently released package,
- refactors `CommitmentKeyExtTrait` to remove unneeded associated type (this is a breaking change, but I've tested [the changes](https://github.com/lurk-lab/lurk-rs/blob/5ddd40f4be4808d7b460688ab90837122cc46eb4/src/proof/nova.rs#L58-L60), which are minimal),
- refactors `EvaluationEngineTrait` to remove unneeded associated type,
> Simplifications to trait structures

- src/circuit.rs
- src/lib.rs
- src/nifs.rs
- src/provider/poseidon.rs
- src/traits/mod.rs
- src/traits/snark.rs
- makes RO traits a tad more approachable by removing the `ROConstants` trait, 
- removes `Sized` bounds (on `Group`, which is used as a generic parameters, they are redundant)
This is a backport of https://github.com/lurk-lab/arecibo/pull/7
> Small RO trait simplification 

- examples/signature.rs
- src/bellpepper/mod.rs
- src/bellpepper/test_shape_cs.rs
- src/circuit.rs
- src/gadgets/nonnative/bignat.rs
- src/lib.rs
- src/provider/keccak.rs
- src/provider/poseidon.rs
- src/spartan/polys/eq.rs
- src/spartan/polys/multilinear.rs
- src/spartan/polys/univariate.rs
- src/traits/circuit.rs
Backports:
- https://github.com/lurk-lab/arecibo/pull/33 
- https://github.com/lurk-lab/arecibo/pull/13 (without the CI changes, as nova/arecibo have starkly different CI)
- https://github.com/lurk-lab/arecibo/pull/12
> Arecibo backports

- Cargo.toml
- src/digest.rs
- src/errors.rs
- src/lib.rs
- src/r1cs.rs
- src/spartan/ppsnark.rs
- src/spartan/snark.rs
The multi-accumulator of SuperNova (introduced in #204, incubated in [Arecibo](https://github.com/lurk-lab/arecibo)) requires introducing digests in a more systematic approach.
This PR introduces a systematic way of creating a Digest for a particular data structure. The pattern is documented in the tests of `src/digest.rs`. Here are the highlights:
- the digest is computed lazily,
- the digest is cached and never needs to be computed more than once,
- structures equipped with digest computation do not require checking if the digest has been correctly populated, or if the deserialized digest matches the structure's bytes,
- there is no need for a convention on hashing the structure with the digest bytes initialized to "zero",
Here's the checklist:
- implement the Digestible trait, which …
> Refactor digest computations (Arecibo backport)

- .clippy.toml
- src/bellpepper/shape_cs.rs
- src/bellpepper/test_shape_cs.rs
- src/circuit.rs
- src/digest.rs
- src/gadgets/r1cs.rs
- src/lib.rs
- src/nifs.rs
- src/provider/ipa_pc.rs
- src/provider/secp_secq.rs
- src/r1cs.rs
- src/spartan/polys/univariate.rs
- src/spartan/sumcheck.rs
- src/traits/circuit.rs
This backports the following small PRs from [Arecibo](https://github.com/lurk-lab/arecibo/):
- https://github.com/lurk-lab/arecibo/pull/54
- https://github.com/lurk-lab/arecibo/pull/55
> Simplify type aliases in tests, map_or expressions, and other simplifications

- Cargo.toml
- examples/minroot.rs
- src/bellpepper/r1cs.rs
- src/lib.rs
- src/nifs.rs
- src/r1cs/mod.rs
- src/r1cs/sparse.rs
- src/r1cs/util.rs
- src/spartan/ppsnark.rs
- src/spartan/snark.rs
Shifts the sparse matrix representation from COO (Coordinate List) to CSR (Compressed Sparse Row).
> [!NOTE]  
> ### COO vs. [CSR](https://en.wikipedia.org/wiki/Sparse_matrix#Compressed_sparse_row_(CSR,_CRS_or_Yale_format))
> In brief, while COO represents a sparse matrix as a list of (row, column, value) tuples, CSR takes a different approach. It makes use of three one-dimensional arrays to store the non-zero elements, the extents of the rows, and the column indices of the elements. The real charm of CSR lies in the contiguity of value representation for the same rows, making it amenable to auto-vectorizers.
The change shows a small 5-10% improvement on recursive proofs, where a matrix-vector product is used in committing to R1CS matrices (and that's on an M2 machine .. on most x86s, …
> Adopt a CSR Representation for Sparse Matrices (Arecibo backport)

- src/bellpepper/shape_cs.rs
- src/bellpepper/test_shape_cs.rs
- src/gadgets/utils.rs
Simple PR getting rid of some clippy attributes.
`clippy::upper_case_acronyms` seems to not trigger for `ShapeCS` and `TestShapeCS`, so this just removes the unnecessary allows for those.
Removing `clippy::needless_range_loop` is a bit more opinionated. Used a `for_each()` to get rid of it but conceptually I can see it being easier for some to read a _for i in X_ notation instead, even though the result is the same. I can undo this change, if the _for i in X_ style is preferable here.
The only clippy attribute that can't be gotten rid of is the `upper_case_acronyms` annotation for `NIFS`.
> refactor: remove clippy attributes

- src/lib.rs
- src/r1cs/mod.rs
Hi there
I found some methods that can be improved.
- replaced **is_sat** equation with `all()`.
- removed unnecessary {}
- unified description
Thank you.
> refactor is_sat and modify comment

- Cargo.toml
- src/r1cs/mod.rs
- src/spartan/ppsnark.rs
PR #229 introduces simplifications to digest computation, but it makes the verifier compute digests on its own, changing the behavior prior to that PR. This PR restores that functionality with an internal type.
> Digest simplifications

- Cargo.toml
- Upgrades the `neptune` dependency to the latest version,
- prior version 11.1.0 broke semver and had to be yanked.
> chore: Upgrade 'neptune' dependency to version 12.0.0

- Cargo.toml
- benches/compressed-snark.rs
- benches/recursive-snark.rs
- benches/sha256.rs
- examples/minroot.rs
- src/lib.rs
- src/r1cs/mod.rs
- src/spartan/ppsnark.rs
Restores digest functionality prior to #238
Makes public interfaces of RecursiveSNARK and CompressedSNARK take references rather than copies (in the prior version, some methods took references whereas others took copies, which is confusing from an API usage perspective).
> Restore digest computation and fix API inconsistency

- src/lib.rs
- src/r1cs/mod.rs
- src/spartan/direct.rs
- src/spartan/ppsnark.rs
- src/spartan/snark.rs
- src/traits/snark.rs
As explained by @zaverucha in https://github.com/microsoft/Spartan2/pull/2 (with edits for precision):
The `R1CSShape` object was being stored in both:
- the `ProverKey` of the `spartan::direct::DirectSNARK`, which generically employs any instance of `RelaxedR1CSSNARKTrait`,
- the `ProverKey` of each of the two `RelaxedR1CSSNARKTrait` implementations in `spartan::{snark, ppsnark}::RelaxedR1CSSNARK`,
- the `PublicParams` that are passed to the proof method of `crate::CompressedSNARK<G1, G2, C1, C2, S1, S2>`, which generically employs any instance of `RelaxedR1CSSNARKTrait`.
IOW, `RelaxedR1CSSNARKTrait` is always accessed through generic structs (`DirectSNARK`, `CompressedSNARK`) which already have a copy of the relevant `R1CSShape`. We store it once in the top level object (`DirectSNARK`'s …
> fix: remove a duplicate `R1CSShape` in the `RelaxedR1CSSNARK`'s chosen `ProverKey` (Arecibo backport)

- src/provider/mod.rs
- src/r1cs/mod.rs
Hi there
I found some methods that can be improved.
- r1cs `is_valid` closure
- provider `cpu_best_multiexp`
**is_valid**
This closure checks whether r1cs matrix row is in range and returns error if invalid.
I modified it and made it returning Err without using `is_err()`.
**cpu_best_multiexp**
According to [rayon doc](https://docs.rs/rayon/latest/rayon/fn.scope.html), parallel iterators are more efficient than scope.
I replaced scope with parallel iterations.
I also avoided unnecessary initialization.
Thank you.
> refactor r1cs::is_valid and provider::cpu_best_multiexp

- src/bellpepper/mod.rs
- src/circuit.rs
- src/gadgets/ecc.rs
- src/gadgets/nonnative/bignat.rs
- src/gadgets/nonnative/util.rs
- src/gadgets/r1cs.rs
- src/gadgets/utils.rs
- src/lib.rs
- src/nifs.rs
- src/provider/poseidon.rs
- src/r1cs/mod.rs
Uses the new `AllocatedNum::alloc_infallible` and eliminates unnecessary wraps with Result.
> Eliminate unnecessary wraps & use alloc_infallible

- Cargo.toml
- src/errors.rs
- src/lib.rs
- src/provider/ipa_pc.rs
- src/spartan/direct.rs
- src/spartan/mod.rs
- src/spartan/polys/identity.rs
- src/spartan/polys/mod.rs
- src/spartan/ppsnark.rs
- src/spartan/sumcheck.rs
Includes experimental optimizations to reduce runtimes and proof size
> Optimize ppsnark

- benches/compressed-snark.rs
- benches/compute-digest.rs
- benches/recursive-snark.rs
- benches/sha256.rs
- examples/minroot.rs
- src/bellpepper/mod.rs
- src/bellpepper/r1cs.rs
- src/circuit.rs
- src/errors.rs
- src/gadgets/ecc.rs
- src/lib.rs
- src/nifs.rs
- src/provider/pedersen.rs
- src/r1cs/mod.rs
- src/spartan/direct.rs
- src/spartan/ppsnark.rs
- src/traits/commitment.rs
- src/traits/snark.rs
The size of the public parameters can vary depending on the method used to process them in a later SNARK. In particular, the memory checking techniques used for computational commitments (Spartan paper section 6) requires larger commitment keys. 
However, because public parameters are created before any SNARK that might use them, their creation as a Rust object is harder to parametrize. So the size of the commitment key is currently set, for all public parameters, to the more conservative (larger) size required in `spartan/ppsnark.rs`.
The current PR allows parametrizing public parameter creation with an optional function of the R1CS shape of the circuits: the size of the parameters will be the min of the usual considerations (min of wire /constraint count) and its output. This function …
> feat: Make commitment key generation configurable with an optional parameter

- src/lib.rs
- src/provider/ipa_pc.rs
- src/provider/mod.rs
Hi there
I added msm test.
In field, it has inverse except zero and that error can be handled by `invert()` method Option trait so I integrated it.
Thank you.
> test: msm test and refactoring

- Cargo.toml
- src/circuit.rs
- src/gadgets/ecc.rs
- src/gadgets/r1cs.rs
- src/lib.rs
- src/r1cs/mod.rs
This PR introduces checks that non-deterministically provided curve points either reside on the curve or they are a point at infinity.
h/t Daniel Dore
> Introduce checks about AllocatedPoint

- Cargo.toml
- src/lib.rs
- src/provider/bn256_grumpkin.rs
- src/provider/mod.rs
- src/provider/pasta.rs
- src/provider/secp_secq.rs
- src/spartan/polys/multilinear.rs
- src/spartan/ppsnark.rs
- src/spartan/sumcheck.rs
Includes some renames for improved clarity
Exposes asm feature of halo2curves
> Cut duplicate code

- examples/minroot.rs
About 10% improvement for the non-release mode. My guess is that examples are typically no run with the `release` flag.
> Small improvement to the minroot example

- src/provider/bn256_grumpkin.rs
- src/provider/mod.rs
- src/provider/pasta.rs
- src/provider/secp_secq.rs
I reduced test and transcript trait code across curve cycle by macros.
**improvement**
curve cycle group methods difference is only vartime_multiscalar_mul.
https://github.com/microsoft/Nova/blob/main/src/provider/mod.rs#L159
If we call msm method through such that `Self::msm()`, we can use same trait between pasta and other cycle pair.
**question**
Is there any reason not to use complete addition for `ecc` gadget?
https://github.com/microsoft/Nova/blob/main/src/gadgets/ecc.rs#L135
We can skip condition branch constraint.
**typo**
`the` duplication
https://eprint.iacr.org/2023/1192.pdf#page=4&zoom=100,100,250
Thank you.
> Reduce duplicate code across different curve cycle providers

- src/spartan/mod.rs
- src/spartan/ppsnark.rs
- src/spartan/snark.rs
This backports the following Arecibo PRs:
- https://github.com/lurk-lab/arecibo/pull/106
- https://github.com/lurk-lab/arecibo/pull/122
This factors out the single-point aggregation of Sumcheck instances implemented at the end of the (non-preprocessing) Spartan SNARk to a couple of auxiliary functions `batch_eval_prove`/`batch_eval_verify`. 
- They will be reused in our upcoming instance of Supernova, so we could include the change here or there, 
- but It's expected this simple change will also ease review and testing of that part of the protocol in the future.
This also performs minor changes the API of a few internal functions which took their argument by value without needing to (as indicated by [tooling](https://rust-lang.github.io/rust-clippy/master/index.html#/needless_pass_by_value …
> refactor: define auxiliary functions for the batching of sumcheck claims (Arecibo backport)

- benches/compressed-snark.rs
- benches/recursive-snark.rs
- src/circuit.rs
This backports the following Arecibo PR: https://github.com/lurk-lab/arecibo/pull/178
At a high level, this offers:
- a better code organization through simple auxiliary functions in the compressed snark benchmark,
- The incremental number of constraints brought on by the primary's augmented circuit was not kept in line with the evolution of that circuit. This updates and uses constants + code comments to make that number more maintainable.
> fix: Improve benchmarks quality (Arecibo backport)

- src/lib.rs
Both of these data are easily accessible, and could be very useful to clients:
* Exposing the last outputs allows us to get the current state of the computation on the prover side without wasting energy recomputing it
* Exposing the number of steps makes it easier to eventually pass `num_steps` into `CompressedSNARK::verify`
> Expose the last outputs and number of steps from RecursiveSNARK

- src/errors.rs
- src/lib.rs
* When a function already returns a `Result`, propagate errors instead of panicking with `expect`
* For `NovaError::SynthesisError`, retain information about the original bellpepper error. Since `NovaError` implements `Clone` but bellpepper's `SynthesisError` does not, we keep the error information as a `String`.
This commit only fixes low-hanging fruit in lib.rs, for functions that already return a `Result` and can easily propagate errors just by replacing `expect(...)` with `?`. There are still many `unwrap()` calls in functions returning `Result` in other modules, particularly gadgets. But I don't understand the code well in those parts, and I suspect some of those `unwrap()`s actually can't fail based on invariants of the code, so it makes perfect sense to leave them as is.
> Improve error handling

- Cargo.toml
- src/spartan/macros.rs
- src/spartan/mod.rs
- src/spartan/polys/eq.rs
- src/spartan/polys/multilinear.rs
- src/spartan/ppsnark.rs
- src/spartan/snark.rs
- src/spartan/sumcheck.rs
- Created a new file `macros.rs` with the implementation of `zip_with` and `zip_with_for_each` macros providing syntactic sugar for zipWith patterns.
- zipWith patterns implemented through the use of the zip_with! macros now resolve to the use of zip_eq, a variant of zip that panics when the iterator arguments are of different length,
- the zip_eq implementation is the native rayon one for parallel iterators, and the one from itertools (see below) for the sequential ones,
- Optimized and refactored functions like `batch_eval_prove` and `batch_eval_verify` in `snark.rs`, methods inside `PolyEvalWitness` and `PolyEvalInstance` in `mod.rs`, and multiple functions in `multilinear.rs` through the use of implemented macros.
- Introduced the use of itertools::Itertools in various files to import …
> refactor: Integrate zip_with macro (Arecibo backport)

- src/circuit.rs
- src/constants.rs
- src/gadgets/r1cs.rs
- src/lib.rs
- src/nifs.rs
This PR is corresponding to issue #56. It removes absorbing of running instance and updates the value of `NUM_FE_FOR_RO` and expected values in tests.
> Remove absorbing of running instance

- src/spartan/mod.rs
- src/spartan/polys/eq.rs
- src/spartan/polys/masked_eq.rs
- src/spartan/polys/mod.rs
- src/spartan/polys/multilinear.rs
- src/spartan/polys/power.rs
- src/spartan/polys/univariate.rs
- src/spartan/ppsnark.rs
- src/spartan/snark.rs
- src/spartan/sumcheck.rs
This gathers the changes to the pre-processing SNARK excerpted from the Supernova implementation in PR #283. The main changes extracted here are the introduction of the masked eq polynomial (and its use fixing [this issue](https://hackmd.io/@adr1anh/Sy08YaVBa)), additional sum-check tooling, removal of two calls to evaluation argument.
Main reference Arecibo PRs:
- https://github.com/lurk-lab/arecibo/pull/106
- https://github.com/lurk-lab/arecibo/pull/131
- https://github.com/lurk-lab/arecibo/pull/174
- https://github.com/lurk-lab/arecibo/pull/182
<details>
<summary> More details (click to expand) </summary>
- Enhancement of polynomial related code in Spartan protocol including new polynomial types, modified existing types, better evaluation methods, and improved polynomial operations.
- …
> refactor: Improve Spartan SNARK polynomial computations and evaluations

- examples/and.rs
- examples/minroot.rs
- src/lib.rs
- src/provider/hyperkzg.rs
- src/provider/mod.rs
Credit (for identifying redundant transcript absorbs): adr1anh
> Rename mlkzg and remove redundant transcript absorbs

- src/provider/hyperkzg.rs
> Optimizations to KZG commitment scheme

- src/spartan/polys/power.rs
- src/spartan/ppsnark.rs
- src/spartan/snark.rs
- src/spartan/sumcheck.rs
> cleanup unused visibility modifiers

- Cargo.toml
- src/errors.rs
- src/lib.rs
- src/nifs.rs
- src/provider/bn256_grumpkin.rs
- src/provider/hyperkzg.rs
- src/provider/ipa_pc.rs
- src/provider/pasta.rs
- src/provider/pedersen.rs
- src/provider/secp_secq.rs
- src/provider/traits.rs
- src/spartan/ppsnark.rs
- src/traits/commitment.rs
The underlying curve libraries that we use (pasta_curves and halo2curves) already serialize group elements in compressed form, so higher-level code such as Nova does not have to manually manage compressed vs. uncompressed forms. This simplifies code.
> avoid explicit compression/decompression

- SECURITY.md
- src/bellpepper/test_shape_cs.rs
- src/gadgets/nonnative/bignat.rs
Hello
While looking through your docs I found and fixed several spelling issues.
Br, Elias.
> docs fix spelling issues

- src/provider/hyperkzg.rs
- src/provider/keccak.rs
- src/provider/traits.rs
There are a few things in hyperkzg that make upstream usage impossible or difficult. In particular, the actual proof is inaccessible in a transparent fashion.
Take a look at the individual commits.
* [feat!: make field elements serialize into transcript in big-endian form](https://github.com/microsoft/Nova/pull/353/commits/8221d2243bece69dc36affc1b43689055b52d054)
- This makes the transcript more compatible with the EVM, which is big-endian
* [feat: expose hyperkzg underlying group](https://github.com/microsoft/Nova/pull/353/commits/f043aabbf12e481c30b1592b76e99f46341f145e)
- This is accomplished via `new` and `into_inner` methods
* [feat: expose hyperkzg argument underlying elements](https://github.com/microsoft/Nova/pull/353/commits/ef432cd171a0162ce7ed2a4c1907725915eaede1)
- This is …
> feat!: improve hyperkzg api

- src/provider/hyperkzg.rs
The `CommitmentKey` fields `ck`, `h`, and `tau_H` are currently private. This PR exposed the fields in the API. This enables users of the Nova project to do things like use different multi-scalar multiplication implementations.
- Implemented a `new` method for the `CommitmentKey` struct to create a new instance.
- Implemented accessor methods for the `ck`, `h`, and `tau_H` fields.
> feat: expose Commitment key fields in API

- src/provider/hyperkzg.rs
One of the first steps that we did when writing a hyperkzg EVM verifier was simplifying the existing Rust verifier to make a port more direct. The code has been written. It doesn't impact anything other than readability. (With the possible exception of the final commit.)
See the individual commits. This PR may be hard to review as a whole, but the individual commits are intended to be very simple.
* The first two commits involve inlining the `kzg_verify_batch` closure, which involves a large `git diff` but very little actual change.
* The remaining commits do various thing. In particular, the main focus is to eliminate "helper" vectors, superfluous variables, mutability, and copy/clone. These all simplify code in general, but in particular make an EVM port much easier.
* The last commit, …
> refactor: simplify hyperkzg verify

- src/provider/hyperkzg.rs
- src/provider/pedersen.rs
This PR refactors the `commit` function in the `hyperkzg` and `pedersen` modules to improve space performance by eliminating the creation of intermediate `scalars` and `bases` vectors. Instead, it directly constructs the required slices for the `vartime_multiscalar_mul` function call and adds the binding factor in a separate step, reducing memory allocations. 
Benchmarks were completed on an Azure VM: `Standard NC24ads A100 v4 (24 vcpus, AMD EPYC 7V13 (Milan) [x86-64], and 220 GiB memory)`
The `compressed-snark` criterion benchmarks show that no change in performance was detected or, in one case, within the noise threshold. Gray relates to the `main` branch, blue relates to the updates in this PR..
- CompressedSNARK-StepCircuitSize-0/Prove 
- CompressedSNARK-StepCircuitSize-6399/Prove 
- …
> refactor: avoid creating intermediate vectors during commit

- examples/and.rs
- src/gadgets/nonnative/mod.rs
There is a clippy warning that is blocking a few PRs - see CI message [here](https://github.com/microsoft/Nova/actions/runs/13392690038/job/37747269290?pr=364) and [here](https://github.com/microsoft/Nova/actions/runs/13595552859/job/38013255593?pr=366). 
This PR fixes the warning. All tests run successfully on local machine.
> fix: clippy warning

- src/provider/hyperkzg.rs
When using serde, the `v` field in the hyperkzg proof has its length encoded three times.
Transposing `v` to use `Vec<[E::Scalar; 3]>` instead of `[Vec<E::Scalar>; 3]` encodes it only once, resulting in a savings of 16 bytes when using bincode-fixint.
> perf: remove 16 bytes from hyperkzg proof by transposing v

- src/frontend/gadgets/mod.rs
- src/frontend/gadgets/multieq.rs
- src/frontend/gadgets/uint32.rs
- Added documentation comments to fix missing_docs errors
- Tested with a [Nova-based SHA256 circuit](https://github.com/avras/nova-sha256)
Fixes #389
> Make uint32 and multieq modules public

- src/provider/hyperkzg.rs
There are some opportunities for performance improvements in the `kzg_open_batch` closure found in the HyperKZG `EvaluationEngine` `Prove` method. Specifically:
- `poly_eval` can use Horner's method for polynomial evaluation
- `scalar_vector_muladd` does not rely on previous calculations, so it can be done in parallel using `rayon`
Criterion benchmarks performed on a `Standard NC96ads A100 v4` machine, not using GPU acceleration, indicate that `ppsnark` showed the largest performance gains while `CompressedSNARK` and `RecursiveSNARK` showed no signification regression of improvements. Results of the benchmarks are in comments below.
> Implement performance improvements to the HyperKZG evaluation engine prove's `kzg_open_batch` closure

- .github/workflows/rust.yml
Updates actions/checkout to the latest stable version v4.
Changes:
Updates all instances of actions/checkout@v2 to actions/checkout@v4
Reference:
Latest version confirmation: https://github.com/actions/checkout/releases/tag/v4.2.2
This update ensures we're using the most recent stable version of the GitHub checkout action across our CI/CD pipelines.
> Updates actions/checkout to the latest stable version v4

- src/provider/hyperkzg.rs
HyperKZG prove's  `kzg_open` closure has `compute_witness_polynomial` which uses Horner's method to compute a witness polynomial. The prover already uses `kzg_open` in a parallel iterator, but the number of iterations is always 3. The `div_by_monomial` implementation uses this limit to its advantage by performing a chunked Horner's method, spreading the computation over more than 3 cores.
Note, `div_by_monomial` does add additional operations. The trade off is that more than 3 cores will be in use. 
Internal Jaeger benchmarks show a 1.24x speed up on a Standard NC96ads A100 v4 when using GPU accelerated code. 
Nova main, `kzg_open` took 178.05ms.
This PR, `kzg_open` took 143.1ms - 1.24x speed up of `kzg_open`.
Criterion benchmarks show an improvement using the GPU on the Standard NC96ads …
> Update the HyperKZG prover's  `compute_witness_polynomial` with a chunk-based Horner algorithm

- Cargo.toml
halo2curves 0.9.0 can be easily used in WASM so it is a good idea to bump it.
> feat: bump halo2curves to 0.9.0

- src/spartan/ppsnark.rs
Accelerated batch inversion in parallel for log-up, inspired by [this blog](https://blog.eryx.co/2024/11/27/The-Power-of-GPU-Parallelization-Applied-to-Cryptography-Primitives.html). Tree depth is 3.
> Parallel Batch Inversion
