Cargo.toml
src/pasta.rs

Let's update to use the latest [Pasta Curves](https://github.com/zcash/pasta_curves).

Use pasta_curves 0.3.0.

---

src/gadgets/ecc.rs
src/gadgets/mod.rs
src/gadgets/r1cs.rs
src/gadgets/utils.rs
src/lib.rs
src/poseidon.rs

make gadgets public, expose coords, cleanup

---

src/circuit.rs
src/gadgets/utils.rs

Change alloc_num_equals arguments to references

---

src/circuit.rs
src/errors.rs
src/gadgets/utils.rs
src/lib.rs
src/poseidon.rs

Verifier's checks

---

examples/minroot.rs
src/lib.rs

Support multiple iterations of MinRoot per step in Nova

MinRoot example improvements

---

Cargo.toml
src/circuit.rs
src/constants.rs
src/gadgets/r1cs.rs
src/lib.rs
src/nifs.rs
src/poseidon.rs
src/traits/mod.rs

This PR updates Nova's RO to use Neptune's sponge construction

integrate with neptune's sponge

---

Cargo.toml
src/bellperson/shape_cs.rs
src/r1cs.rs
src/spartan_with_ipa_pc/mod.rs
src/spartan_with_ipa_pc/polynomial.rs

We, unfortunately, had to drop the wasm feature because bellperson does not anymore have that feature.

Update crate versions

---

.github/workflows/rust.yml
Cargo.toml
benches/compressed-snark.rs
examples/minroot.rs
examples/signature.rs
src/circuit.rs
src/gadgets/r1cs.rs
src/lib.rs
src/nifs.rs
src/provider/ipa_pc.rs
src/provider/mod.rs
src/provider/pasta.rs
src/provider/pedersen.rs
src/provider/poseidon.rs
src/r1cs.rs
src/spartan/mod.rs
src/spartan/polynomial.rs
src/spartan/sumcheck.rs
src/traits/commitment.rs
src/traits/evaluation.rs
src/traits/mod.rs

make spartan generic over the evaluation engine

traits for a vector commitment engine and a polynomial evaluation engine

---

Cargo.toml
examples/signature.rs
src/bellperson/mod.rs
src/bellperson/r1cs.rs
src/bellperson/shape_cs.rs
src/bellperson/solver.rs
src/circuit.rs
src/gadgets/ecc.rs
src/gadgets/nonnative/bignat.rs
src/gadgets/nonnative/util.rs
src/gadgets/r1cs.rs
src/gadgets/utils.rs
src/lib.rs
src/provider/ipa_pc.rs
src/provider/pasta.rs
src/provider/pedersen.rs
src/provider/poseidon.rs
src/r1cs.rs
src/spartan/mod.rs
src/spartan/polynomial.rs
src/spartan/pp.rs
src/spartan/sumcheck.rs

Fixes clippy for #162, as @huitseeker is OOO this week.

chore: update to ff/group 0.13

---

Cargo.toml
examples/signature.rs
src/gadgets/ecc.rs
src/lib.rs
src/provider/bn256_grumpkin.rs
src/provider/keccak.rs
src/provider/pasta.rs
src/spartan/direct.rs
src/spartan/ppsnark.rs

Mainly upgrade `sha3` and `digest` from `0.8` to `0.10` and fix their interface changes. Removed useless `into_iter`

upgrade the dependencies & code clean

---

Cargo.toml
src/gadgets/nonnative/bignat.rs

- Used struct `PolynomialMultiplier` with a corresponding test
- Added `proptest` to dependencies for property-based testing
- Created property-based test to verify big number decomposition under various conditions

test: Tests for polynomial & bignat circuits

---

src/spartan/ppsnark.rs
src/spartan/sumcheck.rs

Found while experimenting with polynomial / iterator APIs in this area. Those should be relatively uncontroversial, but I’m happy to adapt.

Ppsnark refactorings

---

src/spartan/polynomial.rs
src/spartan/ppsnark.rs
src/spartan/snark.rs
src/spartan/sumcheck.rs

See #208 : simplifies some code in `src/spartan`.

More ppsnark refactorings

---

src/circuit.rs
src/provider/ipa_pc.rs

Made a very minor change in this PR. 
Would appreciate a review. Thank you!

Minor tweak

---

src/lib.rs

[microsoft/171](https://github.com/microsoft/Nova/pull/171) introduced enhanced genericity in tests to facilitate unit testing across diverse curve cycles.  Since then, the lib.rs tests, being designed to verify the behaviors of SNARKs instantiated for certain sets of parameters, tend to embed the use of a RelaxedR1CSSnark<G, EE>. They do this under the alias (where the test carefully chooses a specific import path for RelaxedR1CSSnark):
```rust
type S<G> = RelaxedR1CSSnark<G, ipa_pc::EvaluationEgine<G>>
```
Effectively, this constrains the PCS utilized in producing a succinct proof of knowledge of a valid IVC proof to the IPA, even if the only thing the test function needed to be specific about is `RelaxedR1CSSnark`.
Hence, these generic tests then had to accommodate constraints …

refactor: Parametrization of lib.rs Tests for Various Evaluation Engines (Arecibo backport)

---

src/gadgets/nonnative/bignat.rs
src/provider/ipa_pc.rs
src/r1cs/mod.rs

fix typos in comments

---

.github/workflows/rust.yml

Hi there
Github actions check not only build but also test, fmt and clippy so I divided into some parts.
It can run CI check parallelly and save time.
**Question**
I am reading about [Revisiting the Nova Proof System on a Cycle of Curves](https://eprint.iacr.org/2023/969.pdf#page=5&zoom=150,150,750).
Is $R1CS^{(2)} := (A_2,B_2,C_2 \in \mathbb F_2^{n_2 \times m_2})$ correct instead of $R1CS^{(2)} := (A_2,B_2,C_2 \in \mathbb F_1^{n_2 \times m_2})$?
Sorry if I am wrong.
Thank you.

chore: run github actions parallelly

---

Cargo.toml
src/spartan/ppsnark.rs

fix computation of eval_Z, by querying W at the shortened vector

---

Cargo.toml
src/frontend/util_cs/mod.rs
src/frontend/util_cs/test_cs.rs
src/provider/ptau.rs

Additionally: makes test_cs public for testing purposes

release 0.41.0

---

benches/ppsnark.rs
src/provider/hyperkzg.rs
src/provider/mercury.rs
src/provider/mod.rs

[Mercury](https://eprint.iacr.org/2025/385.pdf) is implemented as an evaluation engine.

Mercury PCS

---

src/neutron/relation.rs

remove redundant word in comment

chore: remove redundant word in comment
